language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
   - pip install pyyaml
   - pip install codecov
script: #Putting GRID_PiCaS_Launcher into the pythonpath by force
   - export PYTHONPATH=$PWD:$PYTHONPATH
   - nosetests --with-coverage

after_success:
   - codecov
 

# # command to run tests
