language: python

matrix:
    include:
        - os: linux
          dist: trusty
          python: 2.6
        - os: linux
          dist: xenial
          python: 2.7
        - os: linux
          dist: trusty
          python: 3.3
        - os: linux
          dist: xenial
          python: 3.4
        - os: linux
          dist: xenial
          python: 3.5
        - os: linux
          dist: xenial
          python: 3.6
        - os: linux
          dist: xenial
          python: 3.7
# command to install dependencies
before_install:
   - sudo wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
   - until sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9; do
     echo "GPG key import timed out, sleeping for a bit";
     sleep 20;
     done
   - sudo apt-get update
   - sudo apt-get install -y singularity-container
   - singularity --version
   - pip install pyyaml
   - pip install codecov
script: #Putting GRID_PiCaS_Launcher into the pythonpath by force
   - export PYTHONPATH=$PWD:$PYTHONPATH
   - nosetests --with-coverage

after_success:
   - codecov
 

# # command to run tests
