language: python

matrix:
    include:
        - os: linux
          dist: trusty
          python: 2.6
        - os: linux
          dist: xenial
          python: 2.7
        - os: linux
          dist: trusty
          python: 3.3
        - os: linux
          dist: xenial
          python: 3.4
        - os: linux
          dist: xenial
          python: 3.5
        - os: linux
          dist: xenial
          python: 3.6
        - os: linux
          dist: xenial
          python: 3.7
# command to install dependencies
before_install:
   - sudo wget -O - http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
   - wget -q -O - "https://keyserver.escomposlinux.org/pks/lookup?op=get&search=0xA5D32F012649A5A9" |tail -67| head -65 | sudo apt-key add -
   - sudo apt-get update
   - sudo apt-get install -y singularity-container
   - singularity --version
   - pip install pyyaml
   - pip install nose-cov
   - pip install codecov
script: #Putting GRID_PiCaS_Launcher into the pythonpath by force
   - export PYTHONPATH=$PWD:$PYTHONPATH
   - nosetests --with-coverage

after_success:
   - codecov
 

# # command to run tests
